'Home':
  route_name: 'home'
  path: '/home'

'Page add':
  route_name: 'page_add'
  path: '/node/add/page'

'Error':
  route_name: 'tieto_error_pages.404'
  path: '/error-404'

'Landing pages':
  route_name: 'entity.landing_page.collection'
  path: '/admin/structure/tsp_landing_page'

'Landing page edit':
  route_name: 'entity.landing_page.edit_form'
  path: '/admin/structure/tsp_landing_page/{landing_page}/edit'

'Landing page delete':
  route_name: 'entity.landing_page.delete_form'
  path: '/admin/structure/tsp_landing_page/{landing_page}/delete'

'Landing page add':
  route_name: 'tsp_landing_page.landing_page_add'
  path: '/admin/structure/tsp_landing_page/add'

'Landing page settings':
  route_name: 'tsp_landing_page.landing_page_settings'
  path: '/admin/structure/tsp_landing_page_settings'
